# Generated by Django 4.1.5 on 2023-06-16 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='icon_telegram/', verbose_name='image')),
                ('name', models.TextField(max_length=30, verbose_name='name')),
                ('familia', models.TextField(blank=True, max_length=40, null=True, verbose_name='familia')),
                ('bio', models.TextField(verbose_name='bio')),
                ('phone', models.TextField(verbose_name='telefoh')),
                ('api_id', models.TextField()),
                ('api_hash', models.TextField()),
            ],
            options={
                'verbose_name': 'telegram_acaunt',
                'verbose_name_plural': 'telegram_acaunts',
                'db_table': 'telegram_acaunt',
            },
        ),
        migrations.CreateModel(
            name='Potoci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='zagolovok')),
                ('text', models.TextField(blank=True, null=True, verbose_name='promt')),
                ('paragraf_for_chat', models.TextField(choices=[('test0', 'test0'), ('test1', 'test1')])),
                ('time_stop', models.FloatField()),
                ('user', models.ManyToManyField(to='rabstvo.telegramuser', verbose_name='users')),
            ],
            options={
                'verbose_name': 'potoci',
                'verbose_name_plural': 'potocis',
                'db_table': 'Potoci',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chanel', models.TextField(blank=True, null=True)),
                ('link_for_cahal', models.TextField()),
                ('boti', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rabstvo.telegramuser')),
            ],
            options={
                'verbose_name': 'kanali',
                'verbose_name_plural': 'kanali',
                'db_table': 'kanal',
            },
        ),
    ]
