# Generated by Django 4.1.5 on 2023-06-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potoci',
            name='zagatovlehii_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
