# Generated by Django 4.1.5 on 2023-06-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0002_potoci_zagatovlehii_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potoci',
            name='text',
            field=models.TextField(blank=True, choices=[('prompt', 'Prompt'), ('prompt_2', 'Prompt 2')], default='promt', null=True, verbose_name='promt'),
        ),
        migrations.AlterField(
            model_name='potoci',
            name='zagatovlehii_text',
            field=models.TextField(blank=True, choices=[('prompt', 'Prompt'), ('prompt_2', 'Prompt 2')], default='prompt_2', null=True),
        ),
    ]
