# Generated by Django 4.1.5 on 2023-06-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0003_alter_potoci_text_alter_potoci_zagatovlehii_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potoci',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='promt'),
        ),
        migrations.AlterField(
            model_name='potoci',
            name='zagatovlehii_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
