# Generated by Django 4.1.5 on 2023-06-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0004_alter_potoci_text_alter_potoci_zagatovlehii_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zagatovlehii_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zagatovlehii_text', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(to='rabstvo.telegramuser')),
            ],
        ),
    ]
