# Generated by Django 4.1.5 on 2023-06-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0005_zagatovlehii_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potoci',
            name='paragraf_for_chat',
            field=models.TextField(choices=[('test0', 'test0'), ('test1', 'test1'), ('text_zagatovga', 'text_zagatovga')]),
        ),
    ]
