# Generated by Django 4.2 on 2023-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0006_alter_potoci_paragraf_for_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='potoci',
            name='choiseses_text',
            field=models.TextField(blank=True, choices=[('text_zagatovga', 'text_zagatovga'), ('red', 'red')], null=True),
        ),
        migrations.AlterField(
            model_name='potoci',
            name='paragraf_for_chat',
            field=models.TextField(blank=True, choices=[('test0', 'test0'), ('test1', 'test1')], null=True),
        ),
    ]
