# Generated by Django 4.2 on 2023-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0007_potoci_choiseses_text_alter_potoci_paragraf_for_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potoci',
            name='choiseses_text',
        ),
        migrations.RemoveField(
            model_name='potoci',
            name='zagatovlehii_text',
        ),
        migrations.AlterField(
            model_name='potoci',
            name='paragraf_for_chat',
            field=models.TextField(blank=True, choices=[('test0', 'test0'), ('test1', 'test1'), ('text_zagatovga', 'text_zagatovga')], null=True),
        ),
        migrations.DeleteModel(
            name='Zagatovlehii_text',
        ),
    ]
