# Generated by Django 4.2 on 2023-06-27 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0008_remove_potoci_choiseses_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potoci',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
