# Generated by Django 4.2 on 2023-07-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0009_potoci_last_updated_telegramuser_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_tocken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
            ],
            options={
                'db_table': 'api_tocken',
            },
        ),
        migrations.RemoveField(
            model_name='potoci',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_updated',
        ),
    ]
