# Generated by Django 4.2 on 2023-08-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0010_api_tocken_remove_potoci_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='get_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
