# Generated by Django 4.2 on 2023-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0011_telegramuser_get_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='password_2fa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
