# Generated by Django 4.1.5 on 2023-09-09 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0013_alter_potoci_paragraf_for_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='image',
            field=models.ImageField(default=datetime.date.today, upload_to='icon_telegram/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='name',
            field=models.TextField(default=datetime.date.today, max_length=30, verbose_name='name'),
            preserve_default=False,
        ),
    ]
