# Generated by Django 4.1.5 on 2023-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabstvo', '0014_alter_telegramuser_image_alter_telegramuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='setings',
            field=models.TextField(default='get_channel'),
        ),
    ]
